# generated by datamodel-codegen:
#   filename:  make_Bet.json

from __future__ import annotations

from typing import List
from typing import Optional

from pydantic import BaseModel
from pydantic import Extra


class GameCurrency(BaseModel):
    class Config:
        extra = Extra.forbid

    fa2_address: str
    token_id: Optional[str]


class MakeBetParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    game_currency: GameCurrency
    game_id: str
    bet: str
    guess: List[str]
