# generated by datamodel-codegen:
#   filename:  resolve_Bet.json

from __future__ import annotations

from pydantic import BaseModel
from pydantic import Extra


class ResolveBetParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    game_id: str
    revealed_secret: str
